/**
 * equipment/find-equipment-alerts/1.0
 * As part of the derailment prevention the WDI Wayside detection Integration team  created alerts using sensor data from various wayside detectors and locomotive  onboard detectors. These alerts are used by various teams to prevent derailments  and fix mechanical defects in repair shops. This service is used to retrieve alerts  generated by the WDI CLIPS defect rules engine. The service accepts various selectors in the request and returns alerts that match the request selectors from the system.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * List of alert routings. If not specified all will be returned. Current List of available Options 1) \"T2 Exception\" 2) \"Send to Maintenance System\" 3) \"Popup\" 4) \"TMA Exception\" 5) \"TOMS Exception\" 6) \"Publish the Alert\" 7) \"Update BPT Status\" 8) \"Send Email Notification.\" 9) \"Send to BEM\" 10) \"Send NORA Trigger\" 11) \"LEQ/Engineer Contact\" 12) \"Performance Related\" 13) \"PTC OptStat\" 14) \"Email Notification\" More details can be found on the Wiki  http://wiki.www.uprr.com/confluence/pages/viewpage.action?pageId=152476411
 */
export type AlertRoutingType = string;