/**
 * equipment/find-equipment-alerts/1.0
 * As part of the derailment prevention the WDI Wayside detection Integration team  created alerts using sensor data from various wayside detectors and locomotive  onboard detectors. These alerts are used by various teams to prevent derailments  and fix mechanical defects in repair shops. This service is used to retrieve alerts  generated by the WDI CLIPS defect rules engine. The service accepts various selectors in the request and returns alerts that match the request selectors from the system.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AlertRoutingType } from './alertRoutingType';
import { EquipmentIdentification } from './equipmentIdentification';

/**
 * Provide one to many equipments and searchCriteria in the request.
 */
export interface FindEquipmentAlertsRequest { 
    equipmentIdentificationList: Array<EquipmentIdentification>;
    alertTypeList: Array<FindEquipmentAlertsRequest.AlertTypeListEnum>;
    alertStatusList?: Array<FindEquipmentAlertsRequest.AlertStatusListEnum>;
    alertDefinitionStatusList?: Array<FindEquipmentAlertsRequest.AlertDefinitionStatusListEnum>;
    alertPatternNumberList?: Array<number>;
    alertIdList?: Array<string>;
    alertRoutingTypeList?: Array<AlertRoutingType>;
    /**
     * Alerts open after date. If not specified all will be returned
     */
    alertsOpenAfterDateTime?: string;
    /**
     * Alerts open before date. If not specified will default to sysdate
     */
    alertsOpenBeforeDateTime?: string;
    /**
     * Alerts closed after date. If not specified all will be returned
     */
    alertsClosedAfterDateTime?: string;
    /**
     * Alerts closed before date. If not specified will default to sysdate
     */
    alertsClosedBeforeDateTime?: string;
    /**
     * Axle number on Equipment
     */
    axleSequenceOnEquipment?: number;
    /**
     * Equipment position description L/R/A/B/C
     */
    equipmentSide?: string;
}
export namespace FindEquipmentAlertsRequest {
    export type AlertTypeListEnum = 'LOCO' | 'WAYSIDE' | 'PROBLOG' | 'EW' | 'EA';
    export const AlertTypeListEnum = {
        LOCO: 'LOCO' as AlertTypeListEnum,
        WAYSIDE: 'WAYSIDE' as AlertTypeListEnum,
        PROBLOG: 'PROBLOG' as AlertTypeListEnum,
        EW: 'EW' as AlertTypeListEnum,
        EA: 'EA' as AlertTypeListEnum
    };
    export type AlertStatusListEnum = 'O' | 'C' | 'I' | 'D';
    export const AlertStatusListEnum = {
        O: 'O' as AlertStatusListEnum,
        C: 'C' as AlertStatusListEnum,
        I: 'I' as AlertStatusListEnum,
        D: 'D' as AlertStatusListEnum
    };
    export type AlertDefinitionStatusListEnum = 'PRODUCTION' | 'VERIFICTION' | 'NEW';
    export const AlertDefinitionStatusListEnum = {
        PRODUCTION: 'PRODUCTION' as AlertDefinitionStatusListEnum,
        VERIFICTION: 'VERIFICTION' as AlertDefinitionStatusListEnum,
        NEW: 'NEW' as AlertDefinitionStatusListEnum
    };
}